"""initial schema

Revision ID: 5fb7ac3b159e
Revises: 
Create Date: 2026-07-12 13:49:25.116092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from mortgage_rates.db.schema import create_view_sql


# revision identifiers, used by Alembic.
revision: str = '5fb7ac3b159e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lenders',
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('homepage', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('slug')
    )
    op.create_table('rate_observations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lender_slug', sa.String(), nullable=False),
    sa.Column('observed_date', sa.Date(), nullable=False),
    sa.Column('loan_term_years', sa.Integer(), nullable=False),
    sa.Column('is_fixed', sa.Boolean(), nullable=False),
    sa.Column('arm_fixed_period_years', sa.Integer(), nullable=False, server_default='0'),
    sa.Column('is_fha', sa.Boolean(), nullable=False),
    sa.Column('is_va', sa.Boolean(), nullable=False),
    sa.Column('is_usda', sa.Boolean(), nullable=False),
    sa.Column('is_jumbo', sa.Boolean(), nullable=False),
    sa.Column('interest_rate', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('apr', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('points', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('source_url', sa.String(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['lender_slug'], ['lenders.slug'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lender_slug', 'observed_date', 'loan_term_years', 'is_fixed', 'arm_fixed_period_years', 'is_fha', 'is_va', 'is_usda', 'is_jumbo', name='uq_rate_observation_identity')
    )
    # ### end Alembic commands ###
    op.execute(create_view_sql(op.get_bind().dialect.name))


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP VIEW IF EXISTS v_rate_observations")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rate_observations')
    op.drop_table('lenders')
    # ### end Alembic commands ###
