apiVersion: 1

datasources:
  - name: mortgage_rates_pg
    uid: mortgage_rates_pg
    type: postgres
    access: proxy
    url: postgres:5432
    database: mortgage_rates
    user: mortgage_rates
    isDefault: true
    editable: true
    secureJsonData:
      password: mortgage_rates
    jsonData:
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
